name: VoiceApp
options:
  bundleIdPrefix: com.incept5
  deploymentTarget:
    iOS: "18.4"
  generateEmptyDirectories: true

packages:
  mlx-audio-ios:
    path: Packages/mlx-audio-ios
  mlx-swift-lm:
    url: https://github.com/ml-explore/mlx-swift-lm
    branch: main

schemes:
  VoiceApp:
    build:
      targets:
        VoiceApp: all
        ScreenTimeReport: [build]
    run:
      config: Debug

targets:
  VoiceApp:
    type: application
    platform: iOS
    deploymentTarget:
      iOS: "18.4"
    sources:
      - path: VoiceApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.incept5.VoiceApp
        INFOPLIST_FILE: Info.plist
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "18.4"
        OTHER_SWIFT_FLAGS: "-enable-experimental-feature StrictConcurrency=minimal"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: VoiceApp.entitlements
        DEVELOPMENT_TEAM: NGX9KBXLZ6
    dependencies:
      - package: mlx-audio-ios
        product: MLXAudio
      - package: mlx-swift-lm
        product: MLXLLM
      - package: mlx-swift-lm
        product: MLXLMCommon
      - sdk: Metal.framework
      - sdk: MetalPerformanceShadersGraph.framework
      - sdk: MetalPerformanceShaders.framework
      - sdk: Accelerate.framework
      - sdk: AVFoundation.framework
      - sdk: EventKit.framework
      - target: ScreenTimeReport
    info:
      path: Info.plist
      properties:
        NSMicrophoneUsageDescription: "Voice needs access to your microphone to record voice samples for voice cloning."
        NSCalendarsFullAccessUsageDescription: "Voice reads your calendar to brief you on today's schedule."
        NSRemindersFullAccessUsageDescription: "Voice reads your reminders to include them in your daily brief."
        UILaunchScreen: {}
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight

  ScreenTimeReport:
    type: app-extension
    platform: iOS
    deploymentTarget:
      iOS: "18.4"
    sources:
      - path: ScreenTimeReport
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.incept5.VoiceApp.ScreenTimeReport
        SWIFT_VERSION: "6.0"
        IPHONEOS_DEPLOYMENT_TARGET: "18.4"
        OTHER_SWIFT_FLAGS: "-enable-experimental-feature StrictConcurrency=minimal"
        CODE_SIGN_STYLE: Automatic
        CODE_SIGN_ENTITLEMENTS: ScreenTimeReport/ScreenTimeReport.entitlements
        DEVELOPMENT_TEAM: NGX9KBXLZ6
    info:
      path: ScreenTimeReport/Info.plist
      properties:
        CFBundleDisplayName: ScreenTimeReport
        NSExtension:
          NSExtensionPointIdentifier: com.apple.deviceactivityui.report-extension
